# _config.yml

# Site Settings
title:            LET
description:      LET Workshops and Resources for the UEA
author:           LET # <<< ENSURE THIS IS UPDATED WITH YOUR NAME/ORG

baseurl:          "/LET" # <<< THIS MUST BE EXACTLY THIS

url:              "https://probe973.github.io/LET"

# Jekyll Build Settings
markdown:         kramdown
highlighter:      rouge
#plugins:
  # No SEO plugins needed.

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
